spring:
  application:
    name: Document Management System
  datasource:
    username: postgres
    password: password
    url: "jdbc:postgresql://localhost:5432/dms"
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
encryption:
  salt:
    rounds: 10
jwt:
  algorithm:
    key: "greybeast declares this secure"
  issuer: "greybeast"
  expiryInSeconds: 864000 # 240hr
app:
  frontend-url: "localhost:3000"
  storage:
    location: "upload-dir"